imports:
    - { resource: parameters.yml }

# slim framework configuration
templates.path: ../templates

# slim controller configuration
controller.method_suffix: Action
controller.class_suffix: Controller