imports:
    - { resource: parameters.yml }
    - { resource: services.yml }

# slim framework configuration
templates.path: ../templates

# slim controller configuration
controller.method_suffix: Action
controller.class_suffix: Controller

service:
    default_strategy: singleton